# Generated by Django 4.2.4 on 2024-02-17 17:11

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding_problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='output',
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(default=builtins.print),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(),
        ),
    ]
