# Generated by Django 4.2.4 on 2024-02-17 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding_problems', '0002_remove_testcase_output_problem_expected_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='expected_output',
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_output_file',
            field=models.FileField(default=None, upload_to='expected_output/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='test_case_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='test_cases/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Basic'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
